{application,ymlr,
             [{modules,['Elixir.Ymlr','Elixir.Ymlr.Encode',
                        'Elixir.Ymlr.Encoder','Elixir.Ymlr.Encoder.Any',
                        'Elixir.Ymlr.Encoder.Atom',
                        'Elixir.Ymlr.Encoder.BitString',
                        'Elixir.Ymlr.Encoder.Date',
                        'Elixir.Ymlr.Encoder.DateTime',
                        'Elixir.Ymlr.Encoder.Float',
                        'Elixir.Ymlr.Encoder.Integer',
                        'Elixir.Ymlr.Encoder.List','Elixir.Ymlr.Encoder.Map',
                        'Elixir.Ymlr.Encoder.NaiveDateTime',
                        'Elixir.Ymlr.Encoder.Time',
                        'Elixir.Ymlr.Encoder.Tuple']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A YAML encoder for Elixir"},
              {registered,[]},
              {vsn,"5.1.4"}]}.
