# SPDX-FileCopyrightText: 2019 ash contributors <https://github.com/ash-project/ash/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule Ash.Signals.Transformers.DefineStructs do
  @moduledoc false
  # Defines the argument struct for each signal.
  use Spark.Dsl.Transformer

  alias Spark.Dsl.Transformer

  def transform(dsl_state) do
    module = Transformer.get_persisted(dsl_state, :module)

    dsl_state = Transformer.eval(dsl_state, [], define_index_module(module))

    dsl_state
    |> Transformer.get_entities([:signals])
    |> Enum.reduce({:ok, dsl_state}, fn signal, {:ok, dsl_state} ->
      struct = Module.concat(module, Macro.camelize(to_string(signal.name)))
      signal = %{signal | struct: struct}

      dsl_state =
        dsl_state
        |> Transformer.replace_entity([:signals], signal, &(&1.name == signal.name))
        |> Transformer.eval([], define_struct(struct, signal.arguments, signal))

      {:ok, dsl_state}
    end)
  end

  # Lets `Ash.Signals.Registry.signal_modules/0` find this module.
  defp define_index_module(module) do
    quote do
      Module.create(
        unquote(Ash.Signals.Registry.index_module(module)),
        quote(do: @moduledoc(false)),
        Macro.Env.location(__ENV__)
      )
    end
  end

  defp define_struct(module, fields, signal) do
    fields =
      Enum.map(fields, fn field ->
        opts =
          [
            allow_nil?: field.allow_nil?,
            constraints: field.constraints,
            description: field.description
          ]
          |> then(fn opts ->
            if is_nil(field.default), do: opts, else: Keyword.put(opts, :default, field.default)
          end)
          |> Enum.reject(fn {_, value} -> is_nil(value) end)

        quote do
          field unquote(field.name),
                unquote(Macro.escape(field.type)),
                unquote(Macro.escape(opts))
        end
      end)

    body =
      quote do
        @moduledoc unquote("Generated by the `#{inspect(signal.name)}` signal.")
        use Ash.TypedStruct

        typed_struct do
          (unquote_splicing(fields))
        end
      end

    quote do
      Module.create(unquote(module), unquote(Macro.escape(body)), Macro.Env.location(__ENV__))
    end
  end
end
